# Generated by Django 2.1.3 on 2018-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20181122_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='power_units',
            field=models.CharField(blank=True, help_text='Amount of power that can be generated', max_length=1000, verbose_name='Power Available'),
        ),
        migrations.AlterField(
            model_name='generators',
            name='power_units',
            field=models.CharField(blank=True, help_text='Amount of power that can be generated', max_length=1000, verbose_name='Power Available'),
        ),
        migrations.AlterField(
            model_name='poweravailable',
            name='power_units',
            field=models.CharField(blank=True, help_text='Amount of power that can be generated', max_length=1000, verbose_name='Power Available'),
        ),
        migrations.AlterField(
            model_name='production',
            name='power_units',
            field=models.CharField(blank=True, help_text='Amount of power that can be generated', max_length=1000, verbose_name='Power Available'),
        ),
    ]
