# Generated by Django 2.1.3 on 2018-11-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, help_text='Public ID to identify a individual category.', max_length=30, unique=True, verbose_name='Public Category ID')),
                ('name', models.CharField(help_text='The name of this category.', max_length=250, verbose_name='Name')),
                ('path', models.CharField(editable=False, help_text='The full hierarchical path of this category.', max_length=1000, verbose_name='Full Path')),
                ('level', models.SmallIntegerField(editable=False, help_text='The location in the hierarchy of this category.', verbose_name='Level')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='The parent to this category if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fuel.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ('path',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('fuel_name', models.CharField(help_text='The power plant concerned.', max_length=1000, verbose_name='Fuel')),
                ('fdiscription', models.TextField(blank=True, help_text='Fuel description.', max_length=1000, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(help_text='The Fuel.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Category', verbose_name='Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Powerplant',
            fields=[
                ('plant_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('plant_name', models.CharField(help_text='The power plant concerned.', max_length=1000, verbose_name='Power Plant')),
                ('location', models.CharField(help_text='The location of the power plant concerned.', max_length=1000, verbose_name='PowerPlant location')),
                ('production_capacity', models.PositiveIntegerField()),
                ('available_power', models.PositiveIntegerField()),
                ('category', models.ForeignKey(help_text='The Power Plant.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Category', verbose_name='Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Stockvariation',
            fields=[
                ('sv_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('recorddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storageunit',
            fields=[
                ('storage_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('storage_name', models.CharField(help_text='The power plant storage unit.', max_length=1000, verbose_name='Fuel Tank')),
                ('capacity', models.PositiveIntegerField()),
                ('facility', models.ForeignKey(help_text='The fuel reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Powerplant', verbose_name='Storage')),
            ],
        ),
        migrations.AddField(
            model_name='stockvariation',
            name='storage_unit',
            field=models.ForeignKey(help_text='The fuel reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Storageunit', verbose_name='Storage'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='storage_unit',
            field=models.ForeignKey(help_text='The fuel reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Storageunit', verbose_name='Storage'),
        ),
    ]
