# Generated by Django 2.1.3 on 2018-11-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockvariation',
            old_name='recorddate',
            new_name='record_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_id',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='stockvariation',
            name='sv_id',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='storage_id',
        ),
        migrations.AddField(
            model_name='fuel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerplant',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockvariation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('HFO', 'Heavy Fuel'), ('LFO', 'Light Fuel'), ('HYDR', 'Hydro'), ('THERM', 'Thermal')], help_text='The name of this category.', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[('HFO', 'Heavy Fuel'), ('LFO', 'Light Fuel'), ('HYDR', 'Hydro'), ('THERM', 'Thermal')], default=None, help_text='The parent to this category if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fuel.Category', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='category',
            field=models.ForeignKey(help_text='The Fuel.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='fuel_name',
            field=models.CharField(help_text='The name of fuel type concerned.', max_length=1000, verbose_name='Fuel Name'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='category',
            field=models.ForeignKey(help_text='The Power Plant category.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Category', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_name',
            field=models.CharField(help_text='The name power plant concerned .e.g. Limbe Power plant.', max_length=1000, verbose_name='Power Plant Name'),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='facility',
            field=models.ForeignKey(help_text='The fuel reservoir location or power plant.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Powerplant', verbose_name='Storage Facility'),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='storage_name',
            field=models.CharField(help_text='The name of power plant storage unit.', max_length=1000, verbose_name='Fuel Tank'),
        ),
    ]
