# Generated by Django 2.1.3 on 2018-11-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_auto_20181115_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
