# Generated by Django 2.1.3 on 2018-11-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_remove_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.SmallIntegerField(default=1, editable=False, help_text='The location in the hierarchy of this category.', verbose_name='Level'),
            preserve_default=False,
        ),
    ]
