# Generated by Django 2.1.3 on 2018-11-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='category',
            field=models.ForeignKey(help_text='The Power Plant category.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Category', verbose_name='Category'),
        ),
    ]
