# Generated by Django 2.1.3 on 2018-11-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_auto_20181115_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
