# Generated by Django 2.1.3 on 2018-11-15 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_remove_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The name of this category.', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='The parent to this category if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fuel.Category', verbose_name='Parent'),
        ),
    ]
