# Generated by Django 2.1.3 on 2018-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_auto_20181115_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.SmallIntegerField(default=1, help_text='The location in the hierarchy of this category.', verbose_name='Level'),
            preserve_default=False,
        ),
    ]
