# Generated by Django 2.1.3 on 2018-11-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_category_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(help_text='Units of measurement', max_length=256, verbose_name='Measurement')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='The name of the fuel supplier.', max_length=256, verbose_name="Fuel Supplier's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(help_text='Units of measurement', max_length=256, verbose_name='Measurement')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='storage_unit',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='fuel',
            field=models.ForeignKey(default=0, help_text='The fuel product in the reservoir location or power plant.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Fuel', verbose_name='Fuel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='iniial_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='measurement',
            field=models.CharField(default='Littrs', help_text='Units of measurement', max_length=256, verbose_name='Measurement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='minimum_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='qty_added',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='qty_left',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='qty_removed',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuel',
            name='category',
            field=models.CharField(choices=[('HFO', 'Heavy Fuel'), ('LFO', 'Light Fuel')], help_text='The plant category: HFO or LFO', max_length=256, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='category',
            field=models.CharField(choices=[('HYDR', 'Hydro'), ('THERM', 'Thermal')], help_text='The plant category: hydro or thermal', max_length=256, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='storage_name',
            field=models.CharField(help_text='The name of power plant storage unit .e.go LLP starage.', max_length=1000, verbose_name='Fuel Tank'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='supply',
            name='fuel',
            field=models.ForeignKey(help_text='The fuel added to reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Fuel', verbose_name='Fuel Supplied'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(help_text='The fuel supplied to reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Supplier', verbose_name='Fuel Supplier'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='consumer',
            field=models.ForeignKey(help_text='The fuel reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Powerplant', verbose_name='Consumer'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='fuel',
            field=models.ForeignKey(help_text='The fuel removed from reservoir.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Fuel', verbose_name='Fuel Consumed'),
        ),
    ]
