# Generated by Django 2.1.3 on 2018-11-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0010_auto_20181115_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={'verbose_name': 'Fuel', 'verbose_name_plural': 'Fuel'},
        ),
        migrations.AlterModelOptions(
            name='powerplant',
            options={'verbose_name': 'Power Plant', 'verbose_name_plural': 'Power Plants'},
        ),
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name': 'Storage Unit', 'verbose_name_plural': 'Storage Units'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='supply',
            name='destined_to',
            field=models.ForeignKey(help_text='The fuel storage unit.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Storageunit', verbose_name='Fuel Receptacle'),
        ),
    ]
