# Generated by Django 2.1.3 on 2018-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0011_auto_20181115_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={},
        ),
    ]
