# Generated by Django 2.1.3 on 2018-11-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0012_auto_20181115_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
    ]
