# Generated by Django 2.1.3 on 2018-11-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0014_auto_20181120_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvariation',
            options={'verbose_name': 'Inventory Variation', 'verbose_name_plural': 'Inventory Varations'},
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='storage_unit',
            field=models.ForeignKey(help_text='The record changes in inventory.', on_delete=django.db.models.deletion.CASCADE, to='fuel.Storageunit', verbose_name='Storage Facility'),
        ),
    ]
