# Generated by Django 2.1.3 on 2018-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0017_remove_powerplant_available_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='quantity',
            field=models.CharField(blank=True, help_text='The quantity that has been consumed.', max_length=1000, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='production_capacity',
            field=models.CharField(blank=True, help_text='The production capacity.', max_length=1000, verbose_name='Production Capacity'),
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='iniial_qty',
            field=models.CharField(blank=True, help_text='The quantity left of the inventory on previous day.', max_length=1000, verbose_name='Initial Quantity'),
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='minimum_qty',
            field=models.CharField(blank=True, help_text="The threshold quantity that can't be consumed.", max_length=1000, verbose_name='Threshold'),
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='qty_added',
            field=models.CharField(blank=True, help_text='The quantity added from supply.', max_length=1000, verbose_name='Quantity Supplied'),
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='qty_left',
            field=models.CharField(blank=True, help_text='The quantity left before consumption.', max_length=1000, verbose_name='Quantity on Hand'),
        ),
        migrations.AlterField(
            model_name='stockvariation',
            name='qty_removed',
            field=models.CharField(blank=True, help_text='The quantity to be consumed.', max_length=1000, verbose_name='Quantity Consumed'),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='capacity',
            field=models.CharField(blank=True, help_text='The storage unit for fuel.', max_length=1000, verbose_name='Storage Unit'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.CharField(blank=True, help_text='The Supplied quantity.', max_length=1000, verbose_name='Quantity Supplied'),
        ),
    ]
